import { VideoType } from "./VideoType";

export const VideoData: VideoType[] = [
  {
    name: 'mountaineer',
    index: 0,
    videoSrc: $rawfile('mountaineer.mp4'),
    previewUri: $r('app.media.mountaineer'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'rain',
    index: 1,
    videoSrc: $rawfile('rain.mp4'),
    previewUri: $r('app.media.rain'),
    description: 'This is rain video.',
  },
  {
    name: 'sunrise',
    index: 2,
    videoSrc: $rawfile('sunrise.mp4'),
    previewUri: $r('app.media.sunrise'),
    description: 'This is sunrise video.',
  },
  {
    name: 'mountaineer',
    index: 3,
    videoSrc: $rawfile('mountaineer.mp4'),
    previewUri: $r('app.media.mountaineer'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'rain',
    index: 4,
    videoSrc: $rawfile('rain.mp4'),
    previewUri: $r('app.media.rain'),
    description: 'This is rain video.',
  },
  {
    name: 'sunrise',
    index: 5,
    videoSrc: $rawfile('sunrise.mp4'),
    previewUri: $r('app.media.sunrise'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'mountaineer',
    index: 6,
    videoSrc: $rawfile('mountaineer.mp4'),
    previewUri: $r('app.media.mountaineer'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'rain',
    index: 7,
    videoSrc: $rawfile('rain.mp4'),
    previewUri: $r('app.media.rain'),
    description: 'This is rain video.',
  },
  {
    name: 'sunrise',
    index: 8,
    videoSrc: $rawfile('sunrise.mp4'),
    previewUri: $r('app.media.sunrise'),
    description: 'This is mountaineer video.',
  }
]