/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { VideoType } from "./VideoType";

export const VideoData: VideoType[] = [
  {
    name: 'mountaineer',
    index: 0,
    videoSrc: $rawfile('mountaineer.mp4'),
    previewUri: $r('app.media.mountaineer'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'rain',
    index: 1,
    videoSrc: $rawfile('rain.mp4'),
    previewUri: $r('app.media.rain'),
    description: 'This is rain video.',
  },
  {
    name: 'sunrise',
    index: 2,
    videoSrc: $rawfile('sunrise.mp4'),
    previewUri: $r('app.media.sunrise'),
    description: 'This is sunrise video.',
  },
  {
    name: 'mountaineer',
    index: 3,
    videoSrc: $rawfile('mountaineer.mp4'),
    previewUri: $r('app.media.mountaineer'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'rain',
    index: 4,
    videoSrc: $rawfile('rain.mp4'),
    previewUri: $r('app.media.rain'),
    description: 'This is rain video.',
  },
  {
    name: 'sunrise',
    index: 5,
    videoSrc: $rawfile('sunrise.mp4'),
    previewUri: $r('app.media.sunrise'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'mountaineer',
    index: 6,
    videoSrc: $rawfile('mountaineer.mp4'),
    previewUri: $r('app.media.mountaineer'),
    description: 'This is mountaineer video.',
  },
  {
    name: 'rain',
    index: 7,
    videoSrc: $rawfile('rain.mp4'),
    previewUri: $r('app.media.rain'),
    description: 'This is rain video.',
  },
  {
    name: 'sunrise',
    index: 8,
    videoSrc: $rawfile('sunrise.mp4'),
    previewUri: $r('app.media.sunrise'),
    description: 'This is mountaineer video.',
  }
]